# Generated by Django 3.1 on 2022-05-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220501_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
