# Generated by Django 3.1 on 2022-05-24 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220523_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type_id', models.CharField(max_length=50, verbose_name='Pass Type identifier')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serial number')),
                ('authentication_token', models.CharField(max_length=50, verbose_name='Authentication token')),
                ('data', models.FileField(upload_to='passes', verbose_name='Data (pass file)')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('utime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Apple Wallet Pass',
                'verbose_name_plural': 'Apple Wallet Passes',
                'ordering': ['-pk'],
                'abstract': False,
                'unique_together': {('pass_type_id', 'serial_number')},
            },
        ),
    ]
