# Generated by Django 3.1 on 2022-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti')], default='Cash On Delivery', max_length=20),
        ),
    ]
