# Generated by Django 4.0.2 on 2022-03-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esewa',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='esewa',
            name='date',
        ),
        migrations.RemoveField(
            model_name='esewa',
            name='order',
        ),
        migrations.RemoveField(
            model_name='esewa',
            name='refId',
        ),
        migrations.AddField(
            model_name='esewa',
            name='merchant_id',
            field=models.CharField(default='epay_payment', max_length=100),
        ),
    ]
