# Generated by Django 4.0.2 on 2022-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0002_remove_esewa_amount_remove_esewa_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOCIAL_AUTH_FACEBOOK_KEY', models.CharField(max_length=100)),
                ('SOCIAL_AUTH_FACEBOOK_SECRET', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOCIAL_AUTH_GITHUB_KEY', models.CharField(max_length=100)),
                ('SOCIAL_AUTH_GITHUB_SECRET', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', models.CharField(max_length=100)),
                ('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOCIAL_AUTH_TWITTER_KEY', models.CharField(max_length=100)),
                ('SOCIAL_AUTH_TWITTER_SECRET', models.CharField(max_length=100)),
            ],
        ),
    ]
