# Generated by Django 4.0.2 on 2022-03-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0003_esewa'),
    ]

    operations = [
        migrations.CreateModel(
            name='eSewamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refId', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=64, null=True)),
                ('date', models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esewa.product')),
            ],
        ),
        migrations.DeleteModel(
            name='eSewa',
        ),
    ]
