# Generated by Django 4.0.2 on 2022-03-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0003_facebook_github_google_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='payment_complete',
            new_name='payment_completed',
        ),
    ]
