# Generated by Django 4.0.2 on 2022-03-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0004_rename_payment_complete_product_payment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
