# Generated by Django 4.0.2 on 2022-03-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0004_esewamodel_delete_esewa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eSewamodel',
            new_name='eSewa',
        ),
    ]
