# Generated by Django 4.0.2 on 2022-03-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0005_rename_esewamodel_esewa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eSewa',
            new_name='eSewaa',
        ),
    ]
