# Generated by Django 4.0.2 on 2022-04-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0006_cart_order_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Esewa', 'Esewa')], default='Cash On Delivery', max_length=20),
        ),
    ]
