# Generated by Django 4.0.2 on 2022-03-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0006_rename_esewa_esewaa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eSewaa',
            new_name='eSewa',
        ),
    ]
