# Generated by Django 4.0.2 on 2022-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0007_rename_esewaa_esewa'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
