# Generated by Django 4.0.2 on 2022-04-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0007_order_payment_completed_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_completed',
        ),
    ]
