# Generated by Django 4.0.2 on 2022-04-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0008_remove_subscription_payment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payment_completed',
        ),
    ]
