# Generated by Django 4.0.2 on 2022-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0009_transaction_ipn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Pro', 'Pro')], max_length=100),
        ),
    ]
