# Generated by Django 4.0.2 on 2022-03-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0010_alter_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
