# Generated by Django 4.0.2 on 2022-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0011_alter_cart_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
